# Generated by Django 4.0.3 on 2022-03-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=600)),
                ('status', models.IntegerField(choices=[(1, 'Todo'), (2, 'In Progress'), (3, 'On Hold'), (4, 'Done')])),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasksApi.person')),
            ],
        ),
    ]
